/**
 * Lexical Editor Theme
 * Defines CSS classes for all editor elements
 */
export const editorTheme = {
    ltr: 'lexical-ltr',
    rtl: 'lexical-rtl',
    paragraph: 'lexical-paragraph',
    quote: 'lexical-quote',
    heading: {
        h1: 'lexical-h1',
        h2: 'lexical-h2',
        h3: 'lexical-h3',
        h4: 'lexical-h4',
        h5: 'lexical-h5',
        h6: 'lexical-h6',
    },
    list: {
        nested: {
            listitem: 'lexical-nested-listitem',
        },
        ol: 'lexical-ol',
        ul: 'lexical-ul',
        listitem: 'lexical-listitem',
        listitemChecked: 'lexical-listitem-checked',
        listitemUnchecked: 'lexical-listitem-unchecked',
    },
    hashtag: 'lexical-hashtag',
    image: 'lexical-image',
    link: 'lexical-link',
    text: {
        bold: 'lexical-bold',
        code: 'lexical-code',
        italic: 'lexical-italic',
        strikethrough: 'lexical-strikethrough',
        subscript: 'lexical-subscript',
        superscript: 'lexical-superscript',
        underline: 'lexical-underline',
        underlineStrikethrough: 'lexical-underline-strikethrough',
    },
    code: 'lexical-code-block',
    codeHighlight: {
        atrule: 'lexical-tokenAttr',
        attr: 'lexical-tokenAttr',
        boolean: 'lexical-tokenProperty',
        builtin: 'lexical-tokenSelector',
        cdata: 'lexical-tokenComment',
        char: 'lexical-tokenSelector',
        class: 'lexical-tokenFunction',
        'class-name': 'lexical-tokenFunction',
        comment: 'lexical-tokenComment',
        constant: 'lexical-tokenProperty',
        deleted: 'lexical-tokenProperty',
        doctype: 'lexical-tokenComment',
        entity: 'lexical-tokenOperator',
        function: 'lexical-tokenFunction',
        important: 'lexical-tokenVariable',
        inserted: 'lexical-tokenSelector',
        keyword: 'lexical-tokenAttr',
        namespace: 'lexical-tokenVariable',
        number: 'lexical-tokenProperty',
        operator: 'lexical-tokenOperator',
        prolog: 'lexical-tokenComment',
        property: 'lexical-tokenProperty',
        punctuation: 'lexical-tokenPunctuation',
        regex: 'lexical-tokenVariable',
        selector: 'lexical-tokenSelector',
        string: 'lexical-tokenSelector',
        symbol: 'lexical-tokenProperty',
        tag: 'lexical-tokenProperty',
        url: 'lexical-tokenOperator',
        variable: 'lexical-tokenVariable',
    },
    table: 'lexical-table',
    tableCell: 'lexical-table-cell',
    tableCellHeader: 'lexical-table-cell-header',
    tableRow: 'lexical-table-row',
    tableAddColumns: 'lexical-table-add-columns',
    tableAddRows: 'lexical-table-add-rows',
    tableCellResizer: 'lexical-table-cell-resizer',
    tableCellSelected: 'lexical-table-cell-selected',
};

export default editorTheme;
